services:
  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_DB: streamdash
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5430:5432

volumes:
  postgres_data:
