name = "stream-dash"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-07-30"
compatibility_flags = [
	"nodejs_compat"
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
