name: CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install
          yarn db:generate

      - name: Run checks
        run: |
          yarn check
          yarn lint

      - name: Run tests
        run: yarn build
